#!/usr/bin/env bash
# Install nginx on your web-01
apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World" >> /var/www/html/index.html
service nginx restart
