#!/usr/bin/env bash
# redirection
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www
echo "Holberton School" >> /var/www/html/index.html
sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx start