#!/usr/bin/env bash
# HTTP response contains a custom header
sudo apt-get update
sudo apt-get -y install nginx
echo "add_header X-Served-By $HOSTNAME;" >> /etc/nginx/nginx.conf
sudo service nginx start
