#!/usr/bin/env bash
# HTTP response contains a custom header
sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i '13i\add_header X-Served-By $host;' /etc/nginx/nginx.conf
sudo service nginx start
