#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install -y haproxy
echo "ENABLED=1" >> /etc/default/haproxy
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 35-web-01 34.75.10.160:80 check
   server 35-web-01 35.231.86.187:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
