#!/usr/bin/env bash
# This script displays To infinity and beyond indefinitely.
sigterm_func()
{
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit 0
}
sigquit_func()
{
    rm /var/run/myscript.pid
    exit 0
}
sigint_func()
{
    echo "Y U no love me?!"
}
trap "sigterm_func" SIGTERM
trap "sigquit_func" SIGQUIT
trap "sigint_func" SIGINT
pgrep -f 100-process_and_pid_file >> /var/run/myscript.pid
while true
do
echo "To infinity and beyond"
sleep 2
done
